compound_components: []
estimator_plug_ins:
- /usr/local/share/accelergy/estimation_plug_ins
primitive_components:
- /usr/local/share/accelergy/primitive_component_libs
table_plug_ins:
  roots:
  - /usr/local/share/accelergy/estimation_plug_ins/accelergy-table-based-plug-ins/set_of_table_templates
  - /home/workspace/final-project/example_designs/simple_pim/PIM_estimation_tables
  - /home/workspace/final-project/example_designs/simple_pim/processing-in-memory-design/PIM_estimation_tables
version: 0.3
